version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  go_app:
    image: golang:latest
    container_name: go_container
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: